#!/usr/bin/env python3
"""Generate compact tab-bar labels embedded in Swift (survives Xcode catalog sync)."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
XCSTRINGS = ROOT / "Sources/Shared/Resources/Localizable.xcstrings"
SWIFT_OUT = ROOT / "Sources/Shared/Services/TabBarLabelResolver.swift"
MAX_TAB_LENGTH = 10

TAB_KEYS = {
    "dashboard": "Dashboard",
    "cashFlow": "Cash Flow",
    "investments": "Investments",
    "crypto": "Crypto",
    "settings": "Settings",
}

SHORT_OVERRIDES = {
    "dashboard": {
        "ar": "لوحة",
        "ca": "Tauler",
        "de": "Dashboard",
        "fr": "Tableau",
        "he": "לוח",
        "hr": "Ploča",
        "it": "Dashboard",
        "ms": "Pemuka",
        "ru": "Панель",
        "sv": "Dashboard",
        "tr": "Panel",
        "uk": "Панель",
        "vi": "Tổng quan",
    },
    "cashFlow": {
        "ar": "التدفق",
        "ca": "Flux",
        "el": "Ταμείο",
        "es": "Caja",
        "es-419": "Flujo",
        "fi": "Kassa",
        "fr": "Flux",
        "he": "תזרים",
        "hi": "नकद",
        "hr": "Novac",
        "hu": "Forgalom",
        "it": "Cassa",
        "ms": "Tunai",
        "nb": "Strøm",
        "nl": "Cash",
        "pl": "Przepływ",
        "pt-BR": "Caixa",
        "pt-PT": "Caixa",
        "ro": "Numerar",
        "ru": "Поток",
        "sv": "Kassa",
        "th": "เงินสด",
        "tr": "Nakit",
        "uk": "Потік",
    },
    "investments": {
        "de": "Anlagen",
        "fr": "Placements",
        "it": "Invest.",
    },
    "crypto": {
        "ar": "كريبتو",
        "fr": "Crypto",
        "pt-BR": "Cripto",
        "pt-PT": "Cripto",
        "th": "คริปโต",
        "vi": "Crypto",
    },
    "settings": {
        "de": "Optionen",
        "fr": "Réglages",
        "it": "Opzioni",
    },
}


def resolve_short(tab: str, locale: str, full_value: str, english_short: str) -> str:
    overrides = SHORT_OVERRIDES.get(tab, {})
    if locale in overrides:
        return overrides[locale]
    if len(full_value) <= MAX_TAB_LENGTH:
        return full_value
    return english_short


def build_translations(catalog: dict) -> dict[str, dict[str, str]]:
    strings = catalog.get("strings", {})
    translations: dict[str, dict[str, str]] = {}

    for tab, english_short in TAB_KEYS.items():
        full_entry = strings.get(english_short, {})
        full_locs = full_entry.get("localizations", {})
        tab_locs = {"en": english_short}

        for locale, loc in full_locs.items():
            if locale == "en":
                continue
            full_value = loc.get("stringUnit", {}).get("value", english_short)
            tab_locs[locale] = resolve_short(tab, locale, full_value, english_short)

        translations[tab] = tab_locs

    return translations


def swift_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_swift(translations: dict[str, dict[str, str]]) -> str:
    lines = [
        "// Generated by scripts/add_tab_bar_localizations.py — do not edit by hand.",
        "import Foundation",
        "",
        "enum TabBarLabelResolver {",
        "    enum Tab: String, CaseIterable {",
        "        case dashboard",
        "        case cashFlow",
        "        case investments",
        "        case crypto",
        "        case settings",
        "    }",
        "",
        "    static func title(for tab: Tab, appLanguage: String?) -> String {",
        "        let language = appLanguage ?? \"en\"",
        "        let table = translations[tab] ?? [:]",
        "        return table[language] ?? table[\"en\"] ?? tab.rawValue",
        "    }",
        "",
        "    private static let translations: [Tab: [String: String]] = [",
    ]

    for tab in TAB_KEYS:
        lines.append(f"        .{tab}: [")
        for locale, value in sorted(translations[tab].items()):
            lines.append(f"            {swift_string(locale)}: {swift_string(value)},")
        lines.append("        ],")

    lines.extend([
        "    ]",
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    with XCSTRINGS.open(encoding="utf-8") as handle:
        catalog = json.load(handle)

    translations = build_translations(catalog)
    SWIFT_OUT.write_text(render_swift(translations), encoding="utf-8")

    print(f"Wrote {SWIFT_OUT.relative_to(ROOT)}")
    for tab, locs in translations.items():
        long_entries = [(locale, value) for locale, value in locs.items() if len(value) > MAX_TAB_LENGTH]
        print(f"  {tab}: {len(locs)} locales, {len(long_entries)} still > {MAX_TAB_LENGTH}")
        for locale, value in sorted(long_entries, key=lambda item: -len(item[1]))[:5]:
            print(f"    {locale}: {len(value)} chars — {value}")


if __name__ == "__main__":
    main()
