const fs = require('fs');

const newStrings = [
  "New Transaction", "New Investment", "New Crypto Holding", "Navigate", "Dashboard", "Cash Flow", "Investments", "Crypto", "Settings",
  "Recurring \\(schedule.type.title) due", "\\(schedule.category): \\(amount). Wealth Compass records it while the app is active.", "\\(schedule.category) is scheduled. Open Wealth Compass to review it.", "Touch ID", "Face ID", "Optic ID", "Biometrics", "Enable biometric protection for Wealth Compass.", "Unlock your local Wealth Compass data.", "Biometric authentication is not available on this Mac.", "Wealth Compass", "Unlock with \\(appLock.biometryName)", "Unlock",
  "Validation Failed", "OK", "Invalid API Key", "Welcome to WealthCompass", "Your personal compass for tracking cash flow, investments, and expenses all in one beautifully designed dashboard.", "Continue", "Your Data, Your Privacy", "We don't use central servers. All your financial data is stored locally on your Mac or in your private iCloud. To track live market prices for your assets, you will connect directly to data providers.", "Connect Market Data", "Enter your free API keys to get live stock and crypto prices. This is highly recommended—otherwise, asset prices won't be real or up to date.", "Finnhub API Key (Stocks)", "Paste Finnhub key...", "CoinGecko API Key (Crypto)", "Paste CoinGecko key...", "Validating...", "Get Started", "Skip for now", "Please insert at least one API key, or click 'Skip for now' if you wish to proceed without them.",
  "Refresh Data",
  "Overview", "Positions", "Allocation by Sector", "Allocation by Type", "Allocation by Geography", "Delete Investment?", "Delete \\(investment.symbol)", "Cancel", "This permanently removes \\(investment.symbol) from your investment portfolio.", "Portfolio Value", "Cost Basis", "Profit / Loss", "Performance", "Status • \\(privateCount(sectorCount)) Sectors", "Never", "Top Holdings", "No Investments", "Add stocks, ETFs, bonds, or other positions.", "Quantity", "Current Price", "Last Updated", "Edit Investment", "Delete Investment",
  "Holdings", "Delete Crypto Holding?", "Delete \\(holding.symbol)", "This permanently removes \\(holding.symbol) from your crypto portfolio.", "Crypto Value", "Status • \\(privateCount(uniqueCryptoCount)) Coins", "Crypto Allocation", "Top Performer", "Biggest Loser", "No Crypto Holdings", "Add a holding to track its value.", "Add a holding to track its value and performance.", "Edit Holding", "Delete Holding",
  "Enter an amount greater than zero.", "Enter a custom category name.", "The first occurrence must be in the future.", "The end date cannot be before the first occurrence.", "Transaction", "Type", "Amount (\\(settings.currency.rawValue))", "Description", "Category", "Custom...", "Custom category name", "The category will be saved for future \\(type.title.lowercased()) transactions.", "Schedule", "Repeats", "First Occurrence", "End Date", "Ends", "Notifications", "Notify When Due", "Wealth Compass records due occurrences while the app is active. If the app was closed, missed occurrences are added automatically the next time it opens.", "New Recurring Transaction", "Edit Recurring Transaction", "Save",
  "Amount", "Date", "Enter a category name. It will be saved for future \\(type.title.lowercased()) transactions.", "\\(existing) already exists and will be selected.", "This category will be added to your \\(type.title.lowercased()) categories.", "Identity", "Symbol", "Name", "ISIN / ID", "Classification", "Currency", "Sector", "Geography", "Position", "Average Buy Price", "Investment Transaction Fee", "Fee Type", "Investment Transaction Fee %", "Investment Fee", "The broker or platform fee is added to the position cost basis.", "Technology", "Finance", "Real Estate", "Healthcare", "Energy", "Consumer", "All World", "Other", "US", "Europe", "UK", "Switzerland", "Global", "Emerging Markets", "CoinGecko ID", "Transaction Fee", "Fee Amount", "Fee Percentage", "Calculated Fee", "Edit Crypto Holding",
  "All", "Income", "Expense", "Transactions", "One-Time Transaction", "Recurring Transaction", "Add Transaction", "Monthly Income", "Monthly Expenses", "Net Savings", "Savings Rate", "Total Cash", "Income and expenses by month", "No recent cash flow", "Cash-flow chart concealed", "Month", "Expenses", "\\(cashFlowRange.label) NET", "Expense Categories", "Breakdown of recorded spending", "Expense period", "No expenses for this period", "EXPENSES", "Recent Activity", "Your latest cash flow", "No activity yet", "Recurring Transactions", "Due schedules catch up on open", "Add", "No recurring transactions", "Notifications on", "Notifications off", "Notifications enabled", "Notifications disabled", "Next \\(schedule.nextDueDate.formatted(date: .abbreviated, time: .shortened))", "Paused", "Ends \\(endDate.formatted(date: .abbreviated, time: .omitted))", "No end date", "Pause schedule", "Resume schedule", "Finish schedule", "Edit schedule", "Delete schedule", "Search", "Period", "Showing \\(filteredTransactions.count) of \\(finance.transactions.count)", "Generated from a recurring schedule", "Delete Transaction", "No Transactions", "No Matching Transactions", "Add your first income or expense.", "Change the search, type, or period filters.", "Notifications Disabled", "The schedule was saved, but notifications are not authorized. You can enable them in System Settings and then edit this schedule.", "This permanently removes the \\(transaction.category) transaction from \\(transaction.date.formatted(date: .abbreviated, time: .omitted)).", "Delete", "Delete Recurring Transaction?", "Future \\(schedule.frequency.title.lowercased()) occurrences for \\(schedule.category) will no longer be created.", "Finish Recurring Transaction?", "\\(schedule.category) will disappear from Recurring Transactions and no future occurrences will be inserted automatically.", "Finish", "Food",
  "Your financial horizon", "A clear view of what you own, owe, earn, and spend.", "Privacy on", "Build your first financial view", "Record cash flow or add a position. Wealth Compass will create snapshots and fill this dashboard automatically.", "Investment", "NET WORTH", "for \\(timeRange.rawValue)", "Add another snapshot to see movement over time", "Your net-worth trail starts here", "Adding a transaction or position records a snapshot for this chart.", "Net-worth history concealed", "Turn off Privacy Mode to reveal values and movement.", "Range floor", "Net Worth", "Selected date", "Selected net worth", "Latest snapshot \\(freshnessText(snapshot.date))", "No snapshots yet", "Asset Allocation", "How investable assets are distributed", "No assets to allocate", "Add recorded cash, an investment, or a crypto holding.", "Add Investment", "Allocation concealed", "Values and proportions are hidden.", "Value", "ASSETS", "View Cash Flow", "Record income or an expense to reveal the monthly pattern.", "Monthly amounts and proportions are hidden.", "Top Expense Categories", "Where recorded spending is concentrated", "Choose another period or record an expense.", "Your latest recorded cash movements", "View All", "Your latest income and expenses will appear here.", "just now", "\\(Int(interval / 60))m ago", "\\(Int(interval / (60 * 60)))h ago", "\\(Int(interval / (24 * 60 * 60)))d ago", "3M", "6M", "12M",
  "General", "Data", "iCloud", "Region & Language", "Language", "System", "Base Currency", "Privacy & Security", "Privacy Mode", "Hide financial values throughout Wealth Compass.", "\\(appLock.biometryName) App Lock", "When enabled, Wealth Compass locks when the app is no longer active.", "Custom Categories", "Exchange Rates", "Source", "ECB", "Offline fallback", "1 \\(settings.currency.rawValue)", "Refreshing Exchange Rates", "Refresh Exchange Rates", "\\(error) Cached or fallback rates remain active.", "\\(snapshot.provider). Fetched \\(snapshot.fetchedAt.formatted(date: .abbreviated, time: .shortened)) and cached locally.", "ECB reference rates are refreshed automatically and cached locally for offline use.", "Market Data", "Finnhub API Key", "CoinGecko API Key", "Refreshing Market Data", "Refresh Market Data", "API keys are verified against a live quote before they are stored in the macOS Keychain.", "Import and Export", "Import Behavior", "Merge with local data", "Replace local data", "Import JSON...", "Export JSON...", "Local Storage", "Mode", "Local Only", "Recurring Schedules", "Liabilities", "Snapshots", "Danger Zone", "Delete All Local Data...", "iCloud Sync", "Sync Data with iCloud", "Your financial data stays available locally and syncs across your devices through your private CloudKit database.", "Status", "Manual Actions", "Sync Failed", "Force Sync iCloud", "No custom \\(title.lowercased()) categories yet.", "Remove \\(category)", "Configured", "Not Set", "\\(credential.title) Saved", "\\(message)\\n\\nThe API key was saved securely in Keychain.", "\\(credential.title) Failed", "Finnhub returned a live AAPL quote at \\(quote.price.formatted(.currency(code: Currency.usd.rawValue))).", "CoinGecko returned a live Bitcoin price at \\(quote.price.formatted(.currency(code: Currency.usd.rawValue))).", "\\(credential.title) Removed", "The API key was removed from the macOS Keychain.", "Unable to Remove \\(credential.title)", "Unable to Refresh Market Data", "transaction was", "transactions were", "\\n\\n\\(insertedCount) due recurring \\(transactionWord) added to Cash Flow.", "Import Complete", "Import Failed", "Backup Exported", "Export Failed", "Paste Finnhub API key", "Paste CoinGecko API key", "Apple (AAPL)", "Bitcoin", "Delete all local finance data?", "Remove custom category?", "This permanently removes the local Mac database and its scheduled notifications. This action cannot be undone.", "Existing transactions using \\(category) will keep their current category label.", "Delete All Data", "The key is saved only after \\(credential.testAssetName) returns a live USD price.", "Retrieving \\(credential.testAssetName) price...", "Remove Key", "Verify & Save", "Remove \\(credential.title)?", "The stored credential will be deleted from the macOS Keychain."
];

const filePath = 'Sources/Shared/Resources/Localizable.xcstrings';
const rawData = fs.readFileSync(filePath, 'utf8');
const catalog = JSON.parse(rawData);

let added = 0;

for (let key of newStrings) {
  // In xcstrings, strings with string interpolation \() are usually replaced with %@
  // Let's create the normalized key just in case, but actually the Swift macro `String(localized:)`
  // automatically handles string interpolations by treating \(...) as %@ at extraction time.
  // We can just add the raw key, or the key replaced with %@.
  // It's safer to use the exact string that Swift uses for extraction, which replaces \(...) with %@
  let catalogKey = key.replace(/\\\([^)]+\)/g, '%@');

  if (!catalog.strings[catalogKey]) {
    catalog.strings[catalogKey] = {
      extractionState: "manual",
      localizations: {
        en: {
          stringUnit: {
            state: "translated",
            value: catalogKey
          }
        }
      }
    };
    added++;
  }
}

fs.writeFileSync(filePath, JSON.stringify(catalog, null, 2), 'utf8');
console.log(`Added ${added} new unique strings to Localizable.xcstrings.`);
